/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ioBs89DEH8S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { currentStudents } from "@/app/consts/students";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Students() {
  return (<>
    <section className="py-12 md:py-20">
      <div className="container mx-auto px-4 md:px-6">
        <h2 className="mb-8 text-3xl font-bold md:text-4xl">Current Students</h2>
        <div
          className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">John Doe</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">PhD Candidate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">john.doe@example.com</p>
            <p className="mb-2 font-medium">Research: Quantum Computing</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Joined: 2020</p>
          </div>
          {
            currentStudents.map((student) =>{
              <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">{student.name}</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">PhD Candidate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">john.doe@example.com</p>
            <p className="mb-2 font-medium">Research: Quantum Computing</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Joined: 2020</p>
          </div>
            })
          }


<div class=" flex rounded-lg border bg-card text-card-foreground shadow-sm w-full max-w-md" data-v0-t="card">
  <div class="flex-col space-y-1.5 p-6 flex items-center gap-4">
    <span class="relative flex shrink-0 overflow-hidden rounded-full h-16 w-16">
      <span class="flex h-full w-full items-center justify-center rounded-full bg-muted">JD</span>
    </span>
    <div class="grid gap-1">
      <div class="font-medium">John Doe</div>
      <div class="text-sm text-gray-500 dark:text-gray-400">PhD Student</div>
    </div>
  </div>
  <div class="p-6 grid gap-4">
    <div class="grid gap-1 text-sm">
      <div class="flex items-center justify-between">
        <span>Email:</span>
        <span class="text-gray-500 dark:text-gray-400">john.doe@example.com</span>
      </div>
      <div class="flex items-center justify-between">
        <span>Research Title:</span>
        <span class="text-gray-500 dark:text-gray-400">Innovative Approaches to Machine Learning</span>
      </div>
      <div class="flex items-center justify-between">
        <span>Joined:</span>
        <span class="text-gray-500 dark:text-gray-400">2020</span>
      </div>
      <div class="flex items-center justify-between">
        <span>Completion:</span>
        <span class="text-gray-500 dark:text-gray-400">2024</span>
      </div>
      <div class="flex items-center justify-between">
        <span>Co-Supervisor:</span>
        <span class="text-gray-500 dark:text-gray-400">Dr. Jane Smith</span>
      </div>
      <div class="flex items-center justify-between">
        <span>Status:</span>
        <span class="text-green-500 dark:text-green-400">Ongoing</span>
      </div>
    </div>
  </div>
</div>
          
        </div>
      </div>
    </section>
    <section className="py-12 md:py-20">
      <div className="container mx-auto px-4 md:px-6">
        <h2 className="mb-8 text-3xl font-bold md:text-4xl">Past Students</h2>
        <div
          className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="Sarah Lee" src="/placeholder-avatar.jpg" />
              <AvatarFallback>SL</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">Sarah Lee</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">PhD Graduate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">sarah.lee@example.com</p>
            <p className="mb-2 font-medium">Research: Renewable Energy</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Graduated: 2018</p>
          </div>
          <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="David Kim" src="/placeholder-avatar.jpg" />
              <AvatarFallback>DK</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">David Kim</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">Master's Graduate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">david.kim@example.com</p>
            <p className="mb-2 font-medium">Project: Artificial Intelligence</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Graduated: 2020</p>
          </div>
          <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="Olivia Chen" src="/placeholder-avatar.jpg" />
              <AvatarFallback>OC</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">Olivia Chen</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">PhD Graduate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">olivia.chen@example.com</p>
            <p className="mb-2 font-medium">Research: Quantum Computing</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Graduated: 2019</p>
          </div>
          <div
            className="flex flex-col items-center rounded-lg bg-white p-6 shadow-md dark:bg-gray-950">
            <Avatar className="mb-4 h-20 w-20">
              <AvatarImage alt="Alex Nguyen" src="/placeholder-avatar.jpg" />
              <AvatarFallback>AN</AvatarFallback>
            </Avatar>
            <h3 className="mb-2 text-lg font-semibold">Alex Nguyen</h3>
            <p className="mb-2 text-gray-500 dark:text-gray-400">Master's Graduate</p>
            <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">alex.nguyen@example.com</p>
            <p className="mb-2 font-medium">Project: Sustainable Design</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Graduated: 2021</p>
          </div>
        </div>
      </div>
    </section>
  </>);
}
